# This should be used to provide the database password to Keycloak
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
type: Opaque
stringData:
  dbUrl: "url"
  dbUsername: "username"
  dbPassword: "password"
