apiVersion: v1
kind: Namespace
metadata:
  name: testing-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rbd
  namespace: testing-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cephfs
  namespace: testing-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
