# This is the secret that is used by the cluster issuer to access the Cloudflare API. Should be in the same namespace as cert-manager.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "<api-key>"
