apiVersion: v1
kind: Namespace
metadata:
  name: openobserve

---
apiVersion: v1
kind: Service
metadata:
  name: opob
  namespace: openobserve
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5080
      targetPort: 5080

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opob-1
  namespace: openobserve
  labels:
    kubernetes.io/service-name: opob
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 5080
endpoints:
  - addresses:
      - "192.168.20.55"
    conditions:
      ready: true

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opob-tls
  namespace: openobserve
spec:
  secretName: opob-tls
  dnsNames:
    - opob.cercado.io
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opob
  namespace: openobserve
  annotations:
    external-dns.alpha.kubernetes.io/target: tint.cercado.io
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`opob.cercado.io`)
      priority: 10
      services:
        - name: opob
          kind: Service
          port: 5080
          scheme: http
          passHostHeader: true
  tls:
    secretName: opob-tls
