apiVersion: v1
kind: Namespace
metadata:
  name: openobserve

---
apiVersion: v1
kind: Service
metadata:
  name: opob
  namespace: openobserve
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5080
      targetPort: 5080

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opob-1
  namespace: openobserve
  labels:
    kubernetes.io/service-name: opob
    endpointslice.kubernetes.io/managed-by: cluster-admins
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 5080
endpoints:
  - addresses:
      - "192.168.20.55"
    conditions:
      ready: true

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opob-tls
  namespace: openobserve
spec:
  secretName: opob-tls
  dnsNames:
    - opob.cercado.io
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: opob
  namespace: openobserve
  annotations:
    external-dns.alpha.kubernetes.io/target: tint.cercado.io
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      hostname: opob.cercado.io
      port: 8443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: opob-tls
      allowedRoutes:
        namespaces:
          from: Same

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opob
  namespace: openobserve
spec:
  parentRefs:
    - name: opob
      sectionName: websecure
  hostnames:
    - opob.cercado.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: opob
          port: 5080
