apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for app-of-apps
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - scmProvider:
        cloneProtocol: https
        github:
          appSecretName: creds-1178506064
          # The GitHub organization to scan.
          organization: cercado-dev
          # If true, scan every branch of every repository. If false, scan only the default branch. Defaults to false.
          allBranches: false
        filters:
        - pathsExist:
          - argocd
  template:
    metadata:
      name: "{{ .repository }}-repository"
    spec:
      source:
        repoURL: "{{ .url }}"
        targetRevision: "{{ .branch }}"
        path: argocd
        helm:
          parameters:
          - name: "repository.organization"
            value: "{{.organization }}"
          - name: "repository.name"
            value: "{{.repository }}"
          - name: "repository.id"
            value: "{{.repository_id }}"
          - name: "repository.url"
            value: "{{.url }}"
          - name: "repository.branch"
            value: "{{.branch }}"
          - name: "repository.branchNormalized"
            value: "{{.branchNormalized }}"
          - name: "repository.sha"
            value: "{{.sha}}"
          - name: "repository.shortSha"
            value: "{{.short_sha}}"
          - name: "repository.shortShaSeven"
            value: "{{.short_sha_7}}"
      project: app-of-apps
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
        syncOptions:
          - CreateNamespace=true
