machine:
  network:
    interfaces:
      - deviceSelector:
          driver: virtio_net
          hardwareAddr: "bc:24:11:*"
        addresses:
          - 192.168.20.152/24
        routes:
          - network: 0.0.0.0/0 # The route's network (destination).
            gateway: 192.168.20.1 # The route's gateway (if empty, creates link scope route).
    hostname: talos-ctrl-03
